// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetCustomersIDParams creates a new GetCustomersIDParams object
// with the default values initialized.
func NewGetCustomersIDParams() *GetCustomersIDParams {
	var ()
	return &GetCustomersIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCustomersIDParamsWithTimeout creates a new GetCustomersIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCustomersIDParamsWithTimeout(timeout time.Duration) *GetCustomersIDParams {
	var ()
	return &GetCustomersIDParams{

		timeout: timeout,
	}
}

// NewGetCustomersIDParamsWithContext creates a new GetCustomersIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCustomersIDParamsWithContext(ctx context.Context) *GetCustomersIDParams {
	var ()
	return &GetCustomersIDParams{

		Context: ctx,
	}
}

// NewGetCustomersIDParamsWithHTTPClient creates a new GetCustomersIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCustomersIDParamsWithHTTPClient(client *http.Client) *GetCustomersIDParams {
	var ()
	return &GetCustomersIDParams{
		HTTPClient: client,
	}
}

/*GetCustomersIDParams contains all the parameters to send to the API endpoint
for the get customers ID operation typically these are written to a http.Request
*/
type GetCustomersIDParams struct {

	/*ID
	  ID of customer that needs to be fetched

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get customers ID params
func (o *GetCustomersIDParams) WithTimeout(timeout time.Duration) *GetCustomersIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get customers ID params
func (o *GetCustomersIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get customers ID params
func (o *GetCustomersIDParams) WithContext(ctx context.Context) *GetCustomersIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get customers ID params
func (o *GetCustomersIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get customers ID params
func (o *GetCustomersIDParams) WithHTTPClient(client *http.Client) *GetCustomersIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get customers ID params
func (o *GetCustomersIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get customers ID params
func (o *GetCustomersIDParams) WithID(id int64) *GetCustomersIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get customers ID params
func (o *GetCustomersIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetCustomersIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
