// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/easybill-rest-api/models"
)

// PostCustomersReader is a Reader for the PostCustomers structure.
type PostCustomersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostCustomersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostCustomersCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostCustomersBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewPostCustomersTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostCustomersCreated creates a PostCustomersCreated with default headers values
func NewPostCustomersCreated() *PostCustomersCreated {
	return &PostCustomersCreated{}
}

/*PostCustomersCreated handles this case with default header values.

Successful operation
*/
type PostCustomersCreated struct {
	Payload *models.Customer
}

func (o *PostCustomersCreated) Error() string {
	return fmt.Sprintf("[POST /customers][%d] postCustomersCreated  %+v", 201, o.Payload)
}

func (o *PostCustomersCreated) GetPayload() *models.Customer {
	return o.Payload
}

func (o *PostCustomersCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Customer)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostCustomersBadRequest creates a PostCustomersBadRequest with default headers values
func NewPostCustomersBadRequest() *PostCustomersBadRequest {
	return &PostCustomersBadRequest{}
}

/*PostCustomersBadRequest handles this case with default header values.

Invalid Customer
*/
type PostCustomersBadRequest struct {
}

func (o *PostCustomersBadRequest) Error() string {
	return fmt.Sprintf("[POST /customers][%d] postCustomersBadRequest ", 400)
}

func (o *PostCustomersBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostCustomersTooManyRequests creates a PostCustomersTooManyRequests with default headers values
func NewPostCustomersTooManyRequests() *PostCustomersTooManyRequests {
	return &PostCustomersTooManyRequests{}
}

/*PostCustomersTooManyRequests handles this case with default header values.

Too Many Requests
*/
type PostCustomersTooManyRequests struct {
}

func (o *PostCustomersTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /customers][%d] postCustomersTooManyRequests ", 429)
}

func (o *PostCustomersTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
