// Code generated by go-swagger; DO NOT EDIT.

package contact

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteCustomersCustomerIDContactsIDParams creates a new DeleteCustomersCustomerIDContactsIDParams object
// with the default values initialized.
func NewDeleteCustomersCustomerIDContactsIDParams() *DeleteCustomersCustomerIDContactsIDParams {
	var ()
	return &DeleteCustomersCustomerIDContactsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCustomersCustomerIDContactsIDParamsWithTimeout creates a new DeleteCustomersCustomerIDContactsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteCustomersCustomerIDContactsIDParamsWithTimeout(timeout time.Duration) *DeleteCustomersCustomerIDContactsIDParams {
	var ()
	return &DeleteCustomersCustomerIDContactsIDParams{

		timeout: timeout,
	}
}

// NewDeleteCustomersCustomerIDContactsIDParamsWithContext creates a new DeleteCustomersCustomerIDContactsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteCustomersCustomerIDContactsIDParamsWithContext(ctx context.Context) *DeleteCustomersCustomerIDContactsIDParams {
	var ()
	return &DeleteCustomersCustomerIDContactsIDParams{

		Context: ctx,
	}
}

// NewDeleteCustomersCustomerIDContactsIDParamsWithHTTPClient creates a new DeleteCustomersCustomerIDContactsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteCustomersCustomerIDContactsIDParamsWithHTTPClient(client *http.Client) *DeleteCustomersCustomerIDContactsIDParams {
	var ()
	return &DeleteCustomersCustomerIDContactsIDParams{
		HTTPClient: client,
	}
}

/*DeleteCustomersCustomerIDContactsIDParams contains all the parameters to send to the API endpoint
for the delete customers customer ID contacts ID operation typically these are written to a http.Request
*/
type DeleteCustomersCustomerIDContactsIDParams struct {

	/*CustomerID
	  ID of customer

	*/
	CustomerID int64
	/*ID
	  ID of contact

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete customers customer ID contacts ID params
func (o *DeleteCustomersCustomerIDContactsIDParams) WithTimeout(timeout time.Duration) *DeleteCustomersCustomerIDContactsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete customers customer ID contacts ID params
func (o *DeleteCustomersCustomerIDContactsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete customers customer ID contacts ID params
func (o *DeleteCustomersCustomerIDContactsIDParams) WithContext(ctx context.Context) *DeleteCustomersCustomerIDContactsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete customers customer ID contacts ID params
func (o *DeleteCustomersCustomerIDContactsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete customers customer ID contacts ID params
func (o *DeleteCustomersCustomerIDContactsIDParams) WithHTTPClient(client *http.Client) *DeleteCustomersCustomerIDContactsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete customers customer ID contacts ID params
func (o *DeleteCustomersCustomerIDContactsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerID adds the customerID to the delete customers customer ID contacts ID params
func (o *DeleteCustomersCustomerIDContactsIDParams) WithCustomerID(customerID int64) *DeleteCustomersCustomerIDContactsIDParams {
	o.SetCustomerID(customerID)
	return o
}

// SetCustomerID adds the customerId to the delete customers customer ID contacts ID params
func (o *DeleteCustomersCustomerIDContactsIDParams) SetCustomerID(customerID int64) {
	o.CustomerID = customerID
}

// WithID adds the id to the delete customers customer ID contacts ID params
func (o *DeleteCustomersCustomerIDContactsIDParams) WithID(id int64) *DeleteCustomersCustomerIDContactsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete customers customer ID contacts ID params
func (o *DeleteCustomersCustomerIDContactsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCustomersCustomerIDContactsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customerId
	if err := r.SetPathParam("customerId", swag.FormatInt64(o.CustomerID)); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
