// Code generated by go-swagger; DO NOT EDIT.

package contact

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/kben/easybill-rest-api/models"
)

// NewPostCustomersCustomerIDContactsParams creates a new PostCustomersCustomerIDContactsParams object
// with the default values initialized.
func NewPostCustomersCustomerIDContactsParams() *PostCustomersCustomerIDContactsParams {
	var ()
	return &PostCustomersCustomerIDContactsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostCustomersCustomerIDContactsParamsWithTimeout creates a new PostCustomersCustomerIDContactsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostCustomersCustomerIDContactsParamsWithTimeout(timeout time.Duration) *PostCustomersCustomerIDContactsParams {
	var ()
	return &PostCustomersCustomerIDContactsParams{

		timeout: timeout,
	}
}

// NewPostCustomersCustomerIDContactsParamsWithContext creates a new PostCustomersCustomerIDContactsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostCustomersCustomerIDContactsParamsWithContext(ctx context.Context) *PostCustomersCustomerIDContactsParams {
	var ()
	return &PostCustomersCustomerIDContactsParams{

		Context: ctx,
	}
}

// NewPostCustomersCustomerIDContactsParamsWithHTTPClient creates a new PostCustomersCustomerIDContactsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostCustomersCustomerIDContactsParamsWithHTTPClient(client *http.Client) *PostCustomersCustomerIDContactsParams {
	var ()
	return &PostCustomersCustomerIDContactsParams{
		HTTPClient: client,
	}
}

/*PostCustomersCustomerIDContactsParams contains all the parameters to send to the API endpoint
for the post customers customer ID contacts operation typically these are written to a http.Request
*/
type PostCustomersCustomerIDContactsParams struct {

	/*Body*/
	Body *models.Contact
	/*CustomerID
	  ID of customer

	*/
	CustomerID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post customers customer ID contacts params
func (o *PostCustomersCustomerIDContactsParams) WithTimeout(timeout time.Duration) *PostCustomersCustomerIDContactsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post customers customer ID contacts params
func (o *PostCustomersCustomerIDContactsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post customers customer ID contacts params
func (o *PostCustomersCustomerIDContactsParams) WithContext(ctx context.Context) *PostCustomersCustomerIDContactsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post customers customer ID contacts params
func (o *PostCustomersCustomerIDContactsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post customers customer ID contacts params
func (o *PostCustomersCustomerIDContactsParams) WithHTTPClient(client *http.Client) *PostCustomersCustomerIDContactsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post customers customer ID contacts params
func (o *PostCustomersCustomerIDContactsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post customers customer ID contacts params
func (o *PostCustomersCustomerIDContactsParams) WithBody(body *models.Contact) *PostCustomersCustomerIDContactsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post customers customer ID contacts params
func (o *PostCustomersCustomerIDContactsParams) SetBody(body *models.Contact) {
	o.Body = body
}

// WithCustomerID adds the customerID to the post customers customer ID contacts params
func (o *PostCustomersCustomerIDContactsParams) WithCustomerID(customerID int64) *PostCustomersCustomerIDContactsParams {
	o.SetCustomerID(customerID)
	return o
}

// SetCustomerID adds the customerId to the post customers customer ID contacts params
func (o *PostCustomersCustomerIDContactsParams) SetCustomerID(customerID int64) {
	o.CustomerID = customerID
}

// WriteToRequest writes these params to a swagger request
func (o *PostCustomersCustomerIDContactsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param customerId
	if err := r.SetPathParam("customerId", swag.FormatInt64(o.CustomerID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
