// Code generated by go-swagger; DO NOT EDIT.

package contact

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/easybill-rest-api/models"
)

// PutCustomersCustomerIDContactsIDReader is a Reader for the PutCustomersCustomerIDContactsID structure.
type PutCustomersCustomerIDContactsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutCustomersCustomerIDContactsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutCustomersCustomerIDContactsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutCustomersCustomerIDContactsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewPutCustomersCustomerIDContactsIDTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutCustomersCustomerIDContactsIDOK creates a PutCustomersCustomerIDContactsIDOK with default headers values
func NewPutCustomersCustomerIDContactsIDOK() *PutCustomersCustomerIDContactsIDOK {
	return &PutCustomersCustomerIDContactsIDOK{}
}

/*PutCustomersCustomerIDContactsIDOK handles this case with default header values.

Successful operation
*/
type PutCustomersCustomerIDContactsIDOK struct {
	Payload *models.Contact
}

func (o *PutCustomersCustomerIDContactsIDOK) Error() string {
	return fmt.Sprintf("[PUT /customers/{customerId}/contacts/{id}][%d] putCustomersCustomerIdContactsIdOK  %+v", 200, o.Payload)
}

func (o *PutCustomersCustomerIDContactsIDOK) GetPayload() *models.Contact {
	return o.Payload
}

func (o *PutCustomersCustomerIDContactsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Contact)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutCustomersCustomerIDContactsIDBadRequest creates a PutCustomersCustomerIDContactsIDBadRequest with default headers values
func NewPutCustomersCustomerIDContactsIDBadRequest() *PutCustomersCustomerIDContactsIDBadRequest {
	return &PutCustomersCustomerIDContactsIDBadRequest{}
}

/*PutCustomersCustomerIDContactsIDBadRequest handles this case with default header values.

Invalid contact
*/
type PutCustomersCustomerIDContactsIDBadRequest struct {
}

func (o *PutCustomersCustomerIDContactsIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /customers/{customerId}/contacts/{id}][%d] putCustomersCustomerIdContactsIdBadRequest ", 400)
}

func (o *PutCustomersCustomerIDContactsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutCustomersCustomerIDContactsIDTooManyRequests creates a PutCustomersCustomerIDContactsIDTooManyRequests with default headers values
func NewPutCustomersCustomerIDContactsIDTooManyRequests() *PutCustomersCustomerIDContactsIDTooManyRequests {
	return &PutCustomersCustomerIDContactsIDTooManyRequests{}
}

/*PutCustomersCustomerIDContactsIDTooManyRequests handles this case with default header values.

Too Many Requests
*/
type PutCustomersCustomerIDContactsIDTooManyRequests struct {
}

func (o *PutCustomersCustomerIDContactsIDTooManyRequests) Error() string {
	return fmt.Sprintf("[PUT /customers/{customerId}/contacts/{id}][%d] putCustomersCustomerIdContactsIdTooManyRequests ", 429)
}

func (o *PutCustomersCustomerIDContactsIDTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
