// Code generated by go-swagger; DO NOT EDIT.

package post_box

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeletePostBoxesIDReader is a Reader for the DeletePostBoxesID structure.
type DeletePostBoxesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePostBoxesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeletePostBoxesIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeletePostBoxesIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewDeletePostBoxesIDTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeletePostBoxesIDNoContent creates a DeletePostBoxesIDNoContent with default headers values
func NewDeletePostBoxesIDNoContent() *DeletePostBoxesIDNoContent {
	return &DeletePostBoxesIDNoContent{}
}

/*DeletePostBoxesIDNoContent handles this case with default header values.

Successful operation
*/
type DeletePostBoxesIDNoContent struct {
}

func (o *DeletePostBoxesIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /post-boxes/{id}][%d] deletePostBoxesIdNoContent ", 204)
}

func (o *DeletePostBoxesIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeletePostBoxesIDNotFound creates a DeletePostBoxesIDNotFound with default headers values
func NewDeletePostBoxesIDNotFound() *DeletePostBoxesIDNotFound {
	return &DeletePostBoxesIDNotFound{}
}

/*DeletePostBoxesIDNotFound handles this case with default header values.

Not found
*/
type DeletePostBoxesIDNotFound struct {
}

func (o *DeletePostBoxesIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /post-boxes/{id}][%d] deletePostBoxesIdNotFound ", 404)
}

func (o *DeletePostBoxesIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeletePostBoxesIDTooManyRequests creates a DeletePostBoxesIDTooManyRequests with default headers values
func NewDeletePostBoxesIDTooManyRequests() *DeletePostBoxesIDTooManyRequests {
	return &DeletePostBoxesIDTooManyRequests{}
}

/*DeletePostBoxesIDTooManyRequests handles this case with default header values.

Too Many Requests
*/
type DeletePostBoxesIDTooManyRequests struct {
}

func (o *DeletePostBoxesIDTooManyRequests) Error() string {
	return fmt.Sprintf("[DELETE /post-boxes/{id}][%d] deletePostBoxesIdTooManyRequests ", 429)
}

func (o *DeletePostBoxesIDTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
