// Code generated by go-swagger; DO NOT EDIT.

package post_box

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/easybill-rest-api/models"
)

// GetPostBoxesReader is a Reader for the GetPostBoxes structure.
type GetPostBoxesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPostBoxesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPostBoxesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 429:
		result := NewGetPostBoxesTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPostBoxesOK creates a GetPostBoxesOK with default headers values
func NewGetPostBoxesOK() *GetPostBoxesOK {
	return &GetPostBoxesOK{}
}

/*GetPostBoxesOK handles this case with default header values.

Successful operation
*/
type GetPostBoxesOK struct {
	Payload *models.PostBoxes
}

func (o *GetPostBoxesOK) Error() string {
	return fmt.Sprintf("[GET /post-boxes][%d] getPostBoxesOK  %+v", 200, o.Payload)
}

func (o *GetPostBoxesOK) GetPayload() *models.PostBoxes {
	return o.Payload
}

func (o *GetPostBoxesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PostBoxes)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPostBoxesTooManyRequests creates a GetPostBoxesTooManyRequests with default headers values
func NewGetPostBoxesTooManyRequests() *GetPostBoxesTooManyRequests {
	return &GetPostBoxesTooManyRequests{}
}

/*GetPostBoxesTooManyRequests handles this case with default header values.

Too Many Requests
*/
type GetPostBoxesTooManyRequests struct {
}

func (o *GetPostBoxesTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /post-boxes][%d] getPostBoxesTooManyRequests ", 429)
}

func (o *GetPostBoxesTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
