// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/easybill-rest-api/models"
)

// GetDocumentsIDReader is a Reader for the GetDocumentsID structure.
type GetDocumentsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDocumentsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDocumentsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetDocumentsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetDocumentsIDTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDocumentsIDOK creates a GetDocumentsIDOK with default headers values
func NewGetDocumentsIDOK() *GetDocumentsIDOK {
	return &GetDocumentsIDOK{}
}

/*GetDocumentsIDOK handles this case with default header values.

Successful operation
*/
type GetDocumentsIDOK struct {
	Payload *models.Document
}

func (o *GetDocumentsIDOK) Error() string {
	return fmt.Sprintf("[GET /documents/{id}][%d] getDocumentsIdOK  %+v", 200, o.Payload)
}

func (o *GetDocumentsIDOK) GetPayload() *models.Document {
	return o.Payload
}

func (o *GetDocumentsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Document)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDocumentsIDNotFound creates a GetDocumentsIDNotFound with default headers values
func NewGetDocumentsIDNotFound() *GetDocumentsIDNotFound {
	return &GetDocumentsIDNotFound{}
}

/*GetDocumentsIDNotFound handles this case with default header values.

Not found
*/
type GetDocumentsIDNotFound struct {
}

func (o *GetDocumentsIDNotFound) Error() string {
	return fmt.Sprintf("[GET /documents/{id}][%d] getDocumentsIdNotFound ", 404)
}

func (o *GetDocumentsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDocumentsIDTooManyRequests creates a GetDocumentsIDTooManyRequests with default headers values
func NewGetDocumentsIDTooManyRequests() *GetDocumentsIDTooManyRequests {
	return &GetDocumentsIDTooManyRequests{}
}

/*GetDocumentsIDTooManyRequests handles this case with default header values.

Too Many Requests
*/
type GetDocumentsIDTooManyRequests struct {
}

func (o *GetDocumentsIDTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /documents/{id}][%d] getDocumentsIdTooManyRequests ", 429)
}

func (o *GetDocumentsIDTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
