// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kben/easybill-rest-api/models"
)

// NewPostDocumentsParams creates a new PostDocumentsParams object
// with the default values initialized.
func NewPostDocumentsParams() *PostDocumentsParams {
	var ()
	return &PostDocumentsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostDocumentsParamsWithTimeout creates a new PostDocumentsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostDocumentsParamsWithTimeout(timeout time.Duration) *PostDocumentsParams {
	var ()
	return &PostDocumentsParams{

		timeout: timeout,
	}
}

// NewPostDocumentsParamsWithContext creates a new PostDocumentsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostDocumentsParamsWithContext(ctx context.Context) *PostDocumentsParams {
	var ()
	return &PostDocumentsParams{

		Context: ctx,
	}
}

// NewPostDocumentsParamsWithHTTPClient creates a new PostDocumentsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostDocumentsParamsWithHTTPClient(client *http.Client) *PostDocumentsParams {
	var ()
	return &PostDocumentsParams{
		HTTPClient: client,
	}
}

/*PostDocumentsParams contains all the parameters to send to the API endpoint
for the post documents operation typically these are written to a http.Request
*/
type PostDocumentsParams struct {

	/*Body*/
	Body *models.Document

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post documents params
func (o *PostDocumentsParams) WithTimeout(timeout time.Duration) *PostDocumentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post documents params
func (o *PostDocumentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post documents params
func (o *PostDocumentsParams) WithContext(ctx context.Context) *PostDocumentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post documents params
func (o *PostDocumentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post documents params
func (o *PostDocumentsParams) WithHTTPClient(client *http.Client) *PostDocumentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post documents params
func (o *PostDocumentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post documents params
func (o *PostDocumentsParams) WithBody(body *models.Document) *PostDocumentsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post documents params
func (o *PostDocumentsParams) SetBody(body *models.Document) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostDocumentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
