// Code generated by go-swagger; DO NOT EDIT.

package sepa_payment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteSepaPaymentsIDReader is a Reader for the DeleteSepaPaymentsID structure.
type DeleteSepaPaymentsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSepaPaymentsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteSepaPaymentsIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteSepaPaymentsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewDeleteSepaPaymentsIDTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteSepaPaymentsIDNoContent creates a DeleteSepaPaymentsIDNoContent with default headers values
func NewDeleteSepaPaymentsIDNoContent() *DeleteSepaPaymentsIDNoContent {
	return &DeleteSepaPaymentsIDNoContent{}
}

/*DeleteSepaPaymentsIDNoContent handles this case with default header values.

Successful operation
*/
type DeleteSepaPaymentsIDNoContent struct {
}

func (o *DeleteSepaPaymentsIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /sepa-payments/{id}][%d] deleteSepaPaymentsIdNoContent ", 204)
}

func (o *DeleteSepaPaymentsIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSepaPaymentsIDNotFound creates a DeleteSepaPaymentsIDNotFound with default headers values
func NewDeleteSepaPaymentsIDNotFound() *DeleteSepaPaymentsIDNotFound {
	return &DeleteSepaPaymentsIDNotFound{}
}

/*DeleteSepaPaymentsIDNotFound handles this case with default header values.

Not found
*/
type DeleteSepaPaymentsIDNotFound struct {
}

func (o *DeleteSepaPaymentsIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /sepa-payments/{id}][%d] deleteSepaPaymentsIdNotFound ", 404)
}

func (o *DeleteSepaPaymentsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSepaPaymentsIDTooManyRequests creates a DeleteSepaPaymentsIDTooManyRequests with default headers values
func NewDeleteSepaPaymentsIDTooManyRequests() *DeleteSepaPaymentsIDTooManyRequests {
	return &DeleteSepaPaymentsIDTooManyRequests{}
}

/*DeleteSepaPaymentsIDTooManyRequests handles this case with default header values.

Too Many Requests
*/
type DeleteSepaPaymentsIDTooManyRequests struct {
}

func (o *DeleteSepaPaymentsIDTooManyRequests) Error() string {
	return fmt.Sprintf("[DELETE /sepa-payments/{id}][%d] deleteSepaPaymentsIdTooManyRequests ", 429)
}

func (o *DeleteSepaPaymentsIDTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
