// Code generated by go-swagger; DO NOT EDIT.

package sepa_payment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteSepaPaymentsIDParams creates a new DeleteSepaPaymentsIDParams object
// with the default values initialized.
func NewDeleteSepaPaymentsIDParams() *DeleteSepaPaymentsIDParams {
	var ()
	return &DeleteSepaPaymentsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSepaPaymentsIDParamsWithTimeout creates a new DeleteSepaPaymentsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteSepaPaymentsIDParamsWithTimeout(timeout time.Duration) *DeleteSepaPaymentsIDParams {
	var ()
	return &DeleteSepaPaymentsIDParams{

		timeout: timeout,
	}
}

// NewDeleteSepaPaymentsIDParamsWithContext creates a new DeleteSepaPaymentsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteSepaPaymentsIDParamsWithContext(ctx context.Context) *DeleteSepaPaymentsIDParams {
	var ()
	return &DeleteSepaPaymentsIDParams{

		Context: ctx,
	}
}

// NewDeleteSepaPaymentsIDParamsWithHTTPClient creates a new DeleteSepaPaymentsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteSepaPaymentsIDParamsWithHTTPClient(client *http.Client) *DeleteSepaPaymentsIDParams {
	var ()
	return &DeleteSepaPaymentsIDParams{
		HTTPClient: client,
	}
}

/*DeleteSepaPaymentsIDParams contains all the parameters to send to the API endpoint
for the delete sepa payments ID operation typically these are written to a http.Request
*/
type DeleteSepaPaymentsIDParams struct {

	/*ID
	  ID of SPEA payment

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete sepa payments ID params
func (o *DeleteSepaPaymentsIDParams) WithTimeout(timeout time.Duration) *DeleteSepaPaymentsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete sepa payments ID params
func (o *DeleteSepaPaymentsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete sepa payments ID params
func (o *DeleteSepaPaymentsIDParams) WithContext(ctx context.Context) *DeleteSepaPaymentsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete sepa payments ID params
func (o *DeleteSepaPaymentsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete sepa payments ID params
func (o *DeleteSepaPaymentsIDParams) WithHTTPClient(client *http.Client) *DeleteSepaPaymentsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete sepa payments ID params
func (o *DeleteSepaPaymentsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete sepa payments ID params
func (o *DeleteSepaPaymentsIDParams) WithID(id int64) *DeleteSepaPaymentsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete sepa payments ID params
func (o *DeleteSepaPaymentsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSepaPaymentsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
