// Code generated by go-swagger; DO NOT EDIT.

package sepa_payment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/kben/easybill-rest-api/models"
)

// NewPutSepaPaymentsIDParams creates a new PutSepaPaymentsIDParams object
// with the default values initialized.
func NewPutSepaPaymentsIDParams() *PutSepaPaymentsIDParams {
	var ()
	return &PutSepaPaymentsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutSepaPaymentsIDParamsWithTimeout creates a new PutSepaPaymentsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutSepaPaymentsIDParamsWithTimeout(timeout time.Duration) *PutSepaPaymentsIDParams {
	var ()
	return &PutSepaPaymentsIDParams{

		timeout: timeout,
	}
}

// NewPutSepaPaymentsIDParamsWithContext creates a new PutSepaPaymentsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutSepaPaymentsIDParamsWithContext(ctx context.Context) *PutSepaPaymentsIDParams {
	var ()
	return &PutSepaPaymentsIDParams{

		Context: ctx,
	}
}

// NewPutSepaPaymentsIDParamsWithHTTPClient creates a new PutSepaPaymentsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutSepaPaymentsIDParamsWithHTTPClient(client *http.Client) *PutSepaPaymentsIDParams {
	var ()
	return &PutSepaPaymentsIDParams{
		HTTPClient: client,
	}
}

/*PutSepaPaymentsIDParams contains all the parameters to send to the API endpoint
for the put sepa payments ID operation typically these are written to a http.Request
*/
type PutSepaPaymentsIDParams struct {

	/*Body*/
	Body *models.SEPAPayment
	/*ID
	  ID of SEPA payment

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put sepa payments ID params
func (o *PutSepaPaymentsIDParams) WithTimeout(timeout time.Duration) *PutSepaPaymentsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put sepa payments ID params
func (o *PutSepaPaymentsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put sepa payments ID params
func (o *PutSepaPaymentsIDParams) WithContext(ctx context.Context) *PutSepaPaymentsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put sepa payments ID params
func (o *PutSepaPaymentsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put sepa payments ID params
func (o *PutSepaPaymentsIDParams) WithHTTPClient(client *http.Client) *PutSepaPaymentsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put sepa payments ID params
func (o *PutSepaPaymentsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put sepa payments ID params
func (o *PutSepaPaymentsIDParams) WithBody(body *models.SEPAPayment) *PutSepaPaymentsIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put sepa payments ID params
func (o *PutSepaPaymentsIDParams) SetBody(body *models.SEPAPayment) {
	o.Body = body
}

// WithID adds the id to the put sepa payments ID params
func (o *PutSepaPaymentsIDParams) WithID(id int64) *PutSepaPaymentsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put sepa payments ID params
func (o *PutSepaPaymentsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutSepaPaymentsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
