// Code generated by go-swagger; DO NOT EDIT.

package time_tracking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/kben/easybill-rest-api/models"
)

// NewPutTimeTrackingsIDParams creates a new PutTimeTrackingsIDParams object
// with the default values initialized.
func NewPutTimeTrackingsIDParams() *PutTimeTrackingsIDParams {
	var ()
	return &PutTimeTrackingsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutTimeTrackingsIDParamsWithTimeout creates a new PutTimeTrackingsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutTimeTrackingsIDParamsWithTimeout(timeout time.Duration) *PutTimeTrackingsIDParams {
	var ()
	return &PutTimeTrackingsIDParams{

		timeout: timeout,
	}
}

// NewPutTimeTrackingsIDParamsWithContext creates a new PutTimeTrackingsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutTimeTrackingsIDParamsWithContext(ctx context.Context) *PutTimeTrackingsIDParams {
	var ()
	return &PutTimeTrackingsIDParams{

		Context: ctx,
	}
}

// NewPutTimeTrackingsIDParamsWithHTTPClient creates a new PutTimeTrackingsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutTimeTrackingsIDParamsWithHTTPClient(client *http.Client) *PutTimeTrackingsIDParams {
	var ()
	return &PutTimeTrackingsIDParams{
		HTTPClient: client,
	}
}

/*PutTimeTrackingsIDParams contains all the parameters to send to the API endpoint
for the put time trackings ID operation typically these are written to a http.Request
*/
type PutTimeTrackingsIDParams struct {

	/*Body*/
	Body *models.TimeTracking
	/*ID
	  ID of time tracking

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put time trackings ID params
func (o *PutTimeTrackingsIDParams) WithTimeout(timeout time.Duration) *PutTimeTrackingsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put time trackings ID params
func (o *PutTimeTrackingsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put time trackings ID params
func (o *PutTimeTrackingsIDParams) WithContext(ctx context.Context) *PutTimeTrackingsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put time trackings ID params
func (o *PutTimeTrackingsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put time trackings ID params
func (o *PutTimeTrackingsIDParams) WithHTTPClient(client *http.Client) *PutTimeTrackingsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put time trackings ID params
func (o *PutTimeTrackingsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put time trackings ID params
func (o *PutTimeTrackingsIDParams) WithBody(body *models.TimeTracking) *PutTimeTrackingsIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put time trackings ID params
func (o *PutTimeTrackingsIDParams) SetBody(body *models.TimeTracking) {
	o.Body = body
}

// WithID adds the id to the put time trackings ID params
func (o *PutTimeTrackingsIDParams) WithID(id int64) *PutTimeTrackingsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put time trackings ID params
func (o *PutTimeTrackingsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutTimeTrackingsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
