// Code generated by go-swagger; DO NOT EDIT.

package position

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetPositionsParams creates a new GetPositionsParams object
// with the default values initialized.
func NewGetPositionsParams() *GetPositionsParams {
	var ()
	return &GetPositionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPositionsParamsWithTimeout creates a new GetPositionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPositionsParamsWithTimeout(timeout time.Duration) *GetPositionsParams {
	var ()
	return &GetPositionsParams{

		timeout: timeout,
	}
}

// NewGetPositionsParamsWithContext creates a new GetPositionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPositionsParamsWithContext(ctx context.Context) *GetPositionsParams {
	var ()
	return &GetPositionsParams{

		Context: ctx,
	}
}

// NewGetPositionsParamsWithHTTPClient creates a new GetPositionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPositionsParamsWithHTTPClient(client *http.Client) *GetPositionsParams {
	var ()
	return &GetPositionsParams{
		HTTPClient: client,
	}
}

/*GetPositionsParams contains all the parameters to send to the API endpoint
for the get positions operation typically these are written to a http.Request
*/
type GetPositionsParams struct {

	/*Limit
	  Limited the result. Default is 100. Maximum can be 1000.

	*/
	Limit *int64
	/*Number
	  Filter positions by number. You can add multiple numbers separate by comma like no,no,no.

	*/
	Number *string
	/*Page
	  Set current Page. Default is 1.

	*/
	Page *int64
	/*Type
	  Filter positions by type.

	*/
	Type *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get positions params
func (o *GetPositionsParams) WithTimeout(timeout time.Duration) *GetPositionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get positions params
func (o *GetPositionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get positions params
func (o *GetPositionsParams) WithContext(ctx context.Context) *GetPositionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get positions params
func (o *GetPositionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get positions params
func (o *GetPositionsParams) WithHTTPClient(client *http.Client) *GetPositionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get positions params
func (o *GetPositionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get positions params
func (o *GetPositionsParams) WithLimit(limit *int64) *GetPositionsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get positions params
func (o *GetPositionsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithNumber adds the number to the get positions params
func (o *GetPositionsParams) WithNumber(number *string) *GetPositionsParams {
	o.SetNumber(number)
	return o
}

// SetNumber adds the number to the get positions params
func (o *GetPositionsParams) SetNumber(number *string) {
	o.Number = number
}

// WithPage adds the page to the get positions params
func (o *GetPositionsParams) WithPage(page *int64) *GetPositionsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get positions params
func (o *GetPositionsParams) SetPage(page *int64) {
	o.Page = page
}

// WithType adds the typeVar to the get positions params
func (o *GetPositionsParams) WithType(typeVar *string) *GetPositionsParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the get positions params
func (o *GetPositionsParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *GetPositionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Number != nil {

		// query param number
		var qrNumber string
		if o.Number != nil {
			qrNumber = *o.Number
		}
		qNumber := qrNumber
		if qNumber != "" {
			if err := r.SetQueryParam("number", qNumber); err != nil {
				return err
			}
		}

	}

	if o.Page != nil {

		// query param page
		var qrPage int64
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if o.Type != nil {

		// query param type
		var qrType string
		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {
			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
