// Code generated by go-swagger; DO NOT EDIT.

package position

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/easybill-rest-api/models"
)

// PostPositionsReader is a Reader for the PostPositions structure.
type PostPositionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostPositionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostPositionsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 429:
		result := NewPostPositionsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostPositionsCreated creates a PostPositionsCreated with default headers values
func NewPostPositionsCreated() *PostPositionsCreated {
	return &PostPositionsCreated{}
}

/*PostPositionsCreated handles this case with default header values.

Successful operation
*/
type PostPositionsCreated struct {
	Payload *models.Position
}

func (o *PostPositionsCreated) Error() string {
	return fmt.Sprintf("[POST /positions][%d] postPositionsCreated  %+v", 201, o.Payload)
}

func (o *PostPositionsCreated) GetPayload() *models.Position {
	return o.Payload
}

func (o *PostPositionsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Position)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostPositionsTooManyRequests creates a PostPositionsTooManyRequests with default headers values
func NewPostPositionsTooManyRequests() *PostPositionsTooManyRequests {
	return &PostPositionsTooManyRequests{}
}

/*PostPositionsTooManyRequests handles this case with default header values.

Too Many Requests
*/
type PostPositionsTooManyRequests struct {
}

func (o *PostPositionsTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /positions][%d] postPositionsTooManyRequests ", 429)
}

func (o *PostPositionsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
