// Code generated by go-swagger; DO NOT EDIT.

package position

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kben/easybill-rest-api/models"
)

// NewPostPositionsParams creates a new PostPositionsParams object
// with the default values initialized.
func NewPostPositionsParams() *PostPositionsParams {
	var ()
	return &PostPositionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostPositionsParamsWithTimeout creates a new PostPositionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostPositionsParamsWithTimeout(timeout time.Duration) *PostPositionsParams {
	var ()
	return &PostPositionsParams{

		timeout: timeout,
	}
}

// NewPostPositionsParamsWithContext creates a new PostPositionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostPositionsParamsWithContext(ctx context.Context) *PostPositionsParams {
	var ()
	return &PostPositionsParams{

		Context: ctx,
	}
}

// NewPostPositionsParamsWithHTTPClient creates a new PostPositionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostPositionsParamsWithHTTPClient(client *http.Client) *PostPositionsParams {
	var ()
	return &PostPositionsParams{
		HTTPClient: client,
	}
}

/*PostPositionsParams contains all the parameters to send to the API endpoint
for the post positions operation typically these are written to a http.Request
*/
type PostPositionsParams struct {

	/*Body*/
	Body *models.Position

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post positions params
func (o *PostPositionsParams) WithTimeout(timeout time.Duration) *PostPositionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post positions params
func (o *PostPositionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post positions params
func (o *PostPositionsParams) WithContext(ctx context.Context) *PostPositionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post positions params
func (o *PostPositionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post positions params
func (o *PostPositionsParams) WithHTTPClient(client *http.Client) *PostPositionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post positions params
func (o *PostPositionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post positions params
func (o *PostPositionsParams) WithBody(body *models.Position) *PostPositionsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post positions params
func (o *PostPositionsParams) SetBody(body *models.Position) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostPositionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
