// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteTasksIDReader is a Reader for the DeleteTasksID structure.
type DeleteTasksIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteTasksIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteTasksIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteTasksIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewDeleteTasksIDTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteTasksIDNoContent creates a DeleteTasksIDNoContent with default headers values
func NewDeleteTasksIDNoContent() *DeleteTasksIDNoContent {
	return &DeleteTasksIDNoContent{}
}

/*DeleteTasksIDNoContent handles this case with default header values.

Successful operation
*/
type DeleteTasksIDNoContent struct {
}

func (o *DeleteTasksIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /tasks/{id}][%d] deleteTasksIdNoContent ", 204)
}

func (o *DeleteTasksIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteTasksIDNotFound creates a DeleteTasksIDNotFound with default headers values
func NewDeleteTasksIDNotFound() *DeleteTasksIDNotFound {
	return &DeleteTasksIDNotFound{}
}

/*DeleteTasksIDNotFound handles this case with default header values.

Not found
*/
type DeleteTasksIDNotFound struct {
}

func (o *DeleteTasksIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /tasks/{id}][%d] deleteTasksIdNotFound ", 404)
}

func (o *DeleteTasksIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteTasksIDTooManyRequests creates a DeleteTasksIDTooManyRequests with default headers values
func NewDeleteTasksIDTooManyRequests() *DeleteTasksIDTooManyRequests {
	return &DeleteTasksIDTooManyRequests{}
}

/*DeleteTasksIDTooManyRequests handles this case with default header values.

Too Many Requests
*/
type DeleteTasksIDTooManyRequests struct {
}

func (o *DeleteTasksIDTooManyRequests) Error() string {
	return fmt.Sprintf("[DELETE /tasks/{id}][%d] deleteTasksIdTooManyRequests ", 429)
}

func (o *DeleteTasksIDTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
