// Code generated by go-swagger; DO NOT EDIT.

package document_payment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteDocumentPaymentsIDParams creates a new DeleteDocumentPaymentsIDParams object
// with the default values initialized.
func NewDeleteDocumentPaymentsIDParams() *DeleteDocumentPaymentsIDParams {
	var ()
	return &DeleteDocumentPaymentsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDocumentPaymentsIDParamsWithTimeout creates a new DeleteDocumentPaymentsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteDocumentPaymentsIDParamsWithTimeout(timeout time.Duration) *DeleteDocumentPaymentsIDParams {
	var ()
	return &DeleteDocumentPaymentsIDParams{

		timeout: timeout,
	}
}

// NewDeleteDocumentPaymentsIDParamsWithContext creates a new DeleteDocumentPaymentsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteDocumentPaymentsIDParamsWithContext(ctx context.Context) *DeleteDocumentPaymentsIDParams {
	var ()
	return &DeleteDocumentPaymentsIDParams{

		Context: ctx,
	}
}

// NewDeleteDocumentPaymentsIDParamsWithHTTPClient creates a new DeleteDocumentPaymentsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteDocumentPaymentsIDParamsWithHTTPClient(client *http.Client) *DeleteDocumentPaymentsIDParams {
	var ()
	return &DeleteDocumentPaymentsIDParams{
		HTTPClient: client,
	}
}

/*DeleteDocumentPaymentsIDParams contains all the parameters to send to the API endpoint
for the delete document payments ID operation typically these are written to a http.Request
*/
type DeleteDocumentPaymentsIDParams struct {

	/*ID
	  ID of document payment

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete document payments ID params
func (o *DeleteDocumentPaymentsIDParams) WithTimeout(timeout time.Duration) *DeleteDocumentPaymentsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete document payments ID params
func (o *DeleteDocumentPaymentsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete document payments ID params
func (o *DeleteDocumentPaymentsIDParams) WithContext(ctx context.Context) *DeleteDocumentPaymentsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete document payments ID params
func (o *DeleteDocumentPaymentsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete document payments ID params
func (o *DeleteDocumentPaymentsIDParams) WithHTTPClient(client *http.Client) *DeleteDocumentPaymentsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete document payments ID params
func (o *DeleteDocumentPaymentsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete document payments ID params
func (o *DeleteDocumentPaymentsIDParams) WithID(id int64) *DeleteDocumentPaymentsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete document payments ID params
func (o *DeleteDocumentPaymentsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDocumentPaymentsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
