// Code generated by go-swagger; DO NOT EDIT.

package document_payment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/easybill-rest-api/models"
)

// GetDocumentPaymentsIDReader is a Reader for the GetDocumentPaymentsID structure.
type GetDocumentPaymentsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDocumentPaymentsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDocumentPaymentsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetDocumentPaymentsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetDocumentPaymentsIDTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDocumentPaymentsIDOK creates a GetDocumentPaymentsIDOK with default headers values
func NewGetDocumentPaymentsIDOK() *GetDocumentPaymentsIDOK {
	return &GetDocumentPaymentsIDOK{}
}

/*GetDocumentPaymentsIDOK handles this case with default header values.

Successful operation
*/
type GetDocumentPaymentsIDOK struct {
	Payload *models.DocumentPayment
}

func (o *GetDocumentPaymentsIDOK) Error() string {
	return fmt.Sprintf("[GET /document-payments/{id}][%d] getDocumentPaymentsIdOK  %+v", 200, o.Payload)
}

func (o *GetDocumentPaymentsIDOK) GetPayload() *models.DocumentPayment {
	return o.Payload
}

func (o *GetDocumentPaymentsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DocumentPayment)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDocumentPaymentsIDNotFound creates a GetDocumentPaymentsIDNotFound with default headers values
func NewGetDocumentPaymentsIDNotFound() *GetDocumentPaymentsIDNotFound {
	return &GetDocumentPaymentsIDNotFound{}
}

/*GetDocumentPaymentsIDNotFound handles this case with default header values.

Not found
*/
type GetDocumentPaymentsIDNotFound struct {
}

func (o *GetDocumentPaymentsIDNotFound) Error() string {
	return fmt.Sprintf("[GET /document-payments/{id}][%d] getDocumentPaymentsIdNotFound ", 404)
}

func (o *GetDocumentPaymentsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDocumentPaymentsIDTooManyRequests creates a GetDocumentPaymentsIDTooManyRequests with default headers values
func NewGetDocumentPaymentsIDTooManyRequests() *GetDocumentPaymentsIDTooManyRequests {
	return &GetDocumentPaymentsIDTooManyRequests{}
}

/*GetDocumentPaymentsIDTooManyRequests handles this case with default header values.

Too Many Requests
*/
type GetDocumentPaymentsIDTooManyRequests struct {
}

func (o *GetDocumentPaymentsIDTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /document-payments/{id}][%d] getDocumentPaymentsIdTooManyRequests ", 429)
}

func (o *GetDocumentPaymentsIDTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
