// Code generated by go-swagger; DO NOT EDIT.

package attachment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAttachmentsIDReader is a Reader for the DeleteAttachmentsID structure.
type DeleteAttachmentsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAttachmentsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAttachmentsIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteAttachmentsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewDeleteAttachmentsIDTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteAttachmentsIDNoContent creates a DeleteAttachmentsIDNoContent with default headers values
func NewDeleteAttachmentsIDNoContent() *DeleteAttachmentsIDNoContent {
	return &DeleteAttachmentsIDNoContent{}
}

/*DeleteAttachmentsIDNoContent handles this case with default header values.

Successful operation
*/
type DeleteAttachmentsIDNoContent struct {
}

func (o *DeleteAttachmentsIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /attachments/{id}][%d] deleteAttachmentsIdNoContent ", 204)
}

func (o *DeleteAttachmentsIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAttachmentsIDNotFound creates a DeleteAttachmentsIDNotFound with default headers values
func NewDeleteAttachmentsIDNotFound() *DeleteAttachmentsIDNotFound {
	return &DeleteAttachmentsIDNotFound{}
}

/*DeleteAttachmentsIDNotFound handles this case with default header values.

Not found
*/
type DeleteAttachmentsIDNotFound struct {
}

func (o *DeleteAttachmentsIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /attachments/{id}][%d] deleteAttachmentsIdNotFound ", 404)
}

func (o *DeleteAttachmentsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAttachmentsIDTooManyRequests creates a DeleteAttachmentsIDTooManyRequests with default headers values
func NewDeleteAttachmentsIDTooManyRequests() *DeleteAttachmentsIDTooManyRequests {
	return &DeleteAttachmentsIDTooManyRequests{}
}

/*DeleteAttachmentsIDTooManyRequests handles this case with default header values.

Too Many Requests
*/
type DeleteAttachmentsIDTooManyRequests struct {
}

func (o *DeleteAttachmentsIDTooManyRequests) Error() string {
	return fmt.Sprintf("[DELETE /attachments/{id}][%d] deleteAttachmentsIdTooManyRequests ", 429)
}

func (o *DeleteAttachmentsIDTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
