// Code generated by go-swagger; DO NOT EDIT.

package attachment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAttachmentsIDContentParams creates a new GetAttachmentsIDContentParams object
// with the default values initialized.
func NewGetAttachmentsIDContentParams() *GetAttachmentsIDContentParams {
	var ()
	return &GetAttachmentsIDContentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAttachmentsIDContentParamsWithTimeout creates a new GetAttachmentsIDContentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAttachmentsIDContentParamsWithTimeout(timeout time.Duration) *GetAttachmentsIDContentParams {
	var ()
	return &GetAttachmentsIDContentParams{

		timeout: timeout,
	}
}

// NewGetAttachmentsIDContentParamsWithContext creates a new GetAttachmentsIDContentParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAttachmentsIDContentParamsWithContext(ctx context.Context) *GetAttachmentsIDContentParams {
	var ()
	return &GetAttachmentsIDContentParams{

		Context: ctx,
	}
}

// NewGetAttachmentsIDContentParamsWithHTTPClient creates a new GetAttachmentsIDContentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAttachmentsIDContentParamsWithHTTPClient(client *http.Client) *GetAttachmentsIDContentParams {
	var ()
	return &GetAttachmentsIDContentParams{
		HTTPClient: client,
	}
}

/*GetAttachmentsIDContentParams contains all the parameters to send to the API endpoint
for the get attachments ID content operation typically these are written to a http.Request
*/
type GetAttachmentsIDContentParams struct {

	/*ID
	  ID of attachment

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get attachments ID content params
func (o *GetAttachmentsIDContentParams) WithTimeout(timeout time.Duration) *GetAttachmentsIDContentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get attachments ID content params
func (o *GetAttachmentsIDContentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get attachments ID content params
func (o *GetAttachmentsIDContentParams) WithContext(ctx context.Context) *GetAttachmentsIDContentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get attachments ID content params
func (o *GetAttachmentsIDContentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get attachments ID content params
func (o *GetAttachmentsIDContentParams) WithHTTPClient(client *http.Client) *GetAttachmentsIDContentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get attachments ID content params
func (o *GetAttachmentsIDContentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get attachments ID content params
func (o *GetAttachmentsIDContentParams) WithID(id int64) *GetAttachmentsIDContentParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get attachments ID content params
func (o *GetAttachmentsIDContentParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetAttachmentsIDContentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
