// Code generated by go-swagger; DO NOT EDIT.

package attachment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/kben/easybill-rest-api/models"
)

// NewPutAttachmentsIDParams creates a new PutAttachmentsIDParams object
// with the default values initialized.
func NewPutAttachmentsIDParams() *PutAttachmentsIDParams {
	var ()
	return &PutAttachmentsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutAttachmentsIDParamsWithTimeout creates a new PutAttachmentsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutAttachmentsIDParamsWithTimeout(timeout time.Duration) *PutAttachmentsIDParams {
	var ()
	return &PutAttachmentsIDParams{

		timeout: timeout,
	}
}

// NewPutAttachmentsIDParamsWithContext creates a new PutAttachmentsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutAttachmentsIDParamsWithContext(ctx context.Context) *PutAttachmentsIDParams {
	var ()
	return &PutAttachmentsIDParams{

		Context: ctx,
	}
}

// NewPutAttachmentsIDParamsWithHTTPClient creates a new PutAttachmentsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutAttachmentsIDParamsWithHTTPClient(client *http.Client) *PutAttachmentsIDParams {
	var ()
	return &PutAttachmentsIDParams{
		HTTPClient: client,
	}
}

/*PutAttachmentsIDParams contains all the parameters to send to the API endpoint
for the put attachments ID operation typically these are written to a http.Request
*/
type PutAttachmentsIDParams struct {

	/*Body*/
	Body *models.Attachment
	/*ID
	  ID of attachment

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put attachments ID params
func (o *PutAttachmentsIDParams) WithTimeout(timeout time.Duration) *PutAttachmentsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put attachments ID params
func (o *PutAttachmentsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put attachments ID params
func (o *PutAttachmentsIDParams) WithContext(ctx context.Context) *PutAttachmentsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put attachments ID params
func (o *PutAttachmentsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put attachments ID params
func (o *PutAttachmentsIDParams) WithHTTPClient(client *http.Client) *PutAttachmentsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put attachments ID params
func (o *PutAttachmentsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put attachments ID params
func (o *PutAttachmentsIDParams) WithBody(body *models.Attachment) *PutAttachmentsIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put attachments ID params
func (o *PutAttachmentsIDParams) SetBody(body *models.Attachment) {
	o.Body = body
}

// WithID adds the id to the put attachments ID params
func (o *PutAttachmentsIDParams) WithID(id int64) *PutAttachmentsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put attachments ID params
func (o *PutAttachmentsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutAttachmentsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
