// Code generated by go-swagger; DO NOT EDIT.

package text_template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/easybill-rest-api/models"
)

// GetTextTemplatesReader is a Reader for the GetTextTemplates structure.
type GetTextTemplatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTextTemplatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTextTemplatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 429:
		result := NewGetTextTemplatesTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTextTemplatesOK creates a GetTextTemplatesOK with default headers values
func NewGetTextTemplatesOK() *GetTextTemplatesOK {
	return &GetTextTemplatesOK{}
}

/*GetTextTemplatesOK handles this case with default header values.

Successful operation
*/
type GetTextTemplatesOK struct {
	Payload *models.TextTemplates
}

func (o *GetTextTemplatesOK) Error() string {
	return fmt.Sprintf("[GET /text-templates][%d] getTextTemplatesOK  %+v", 200, o.Payload)
}

func (o *GetTextTemplatesOK) GetPayload() *models.TextTemplates {
	return o.Payload
}

func (o *GetTextTemplatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TextTemplates)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTextTemplatesTooManyRequests creates a GetTextTemplatesTooManyRequests with default headers values
func NewGetTextTemplatesTooManyRequests() *GetTextTemplatesTooManyRequests {
	return &GetTextTemplatesTooManyRequests{}
}

/*GetTextTemplatesTooManyRequests handles this case with default header values.

Too Many Requests
*/
type GetTextTemplatesTooManyRequests struct {
}

func (o *GetTextTemplatesTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /text-templates][%d] getTextTemplatesTooManyRequests ", 429)
}

func (o *GetTextTemplatesTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
