// Code generated by go-swagger; DO NOT EDIT.

package text_template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetTextTemplatesIDParams creates a new GetTextTemplatesIDParams object
// with the default values initialized.
func NewGetTextTemplatesIDParams() *GetTextTemplatesIDParams {
	var ()
	return &GetTextTemplatesIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTextTemplatesIDParamsWithTimeout creates a new GetTextTemplatesIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTextTemplatesIDParamsWithTimeout(timeout time.Duration) *GetTextTemplatesIDParams {
	var ()
	return &GetTextTemplatesIDParams{

		timeout: timeout,
	}
}

// NewGetTextTemplatesIDParamsWithContext creates a new GetTextTemplatesIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTextTemplatesIDParamsWithContext(ctx context.Context) *GetTextTemplatesIDParams {
	var ()
	return &GetTextTemplatesIDParams{

		Context: ctx,
	}
}

// NewGetTextTemplatesIDParamsWithHTTPClient creates a new GetTextTemplatesIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTextTemplatesIDParamsWithHTTPClient(client *http.Client) *GetTextTemplatesIDParams {
	var ()
	return &GetTextTemplatesIDParams{
		HTTPClient: client,
	}
}

/*GetTextTemplatesIDParams contains all the parameters to send to the API endpoint
for the get text templates ID operation typically these are written to a http.Request
*/
type GetTextTemplatesIDParams struct {

	/*ID
	  ID of text template

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get text templates ID params
func (o *GetTextTemplatesIDParams) WithTimeout(timeout time.Duration) *GetTextTemplatesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get text templates ID params
func (o *GetTextTemplatesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get text templates ID params
func (o *GetTextTemplatesIDParams) WithContext(ctx context.Context) *GetTextTemplatesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get text templates ID params
func (o *GetTextTemplatesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get text templates ID params
func (o *GetTextTemplatesIDParams) WithHTTPClient(client *http.Client) *GetTextTemplatesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get text templates ID params
func (o *GetTextTemplatesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get text templates ID params
func (o *GetTextTemplatesIDParams) WithID(id int64) *GetTextTemplatesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get text templates ID params
func (o *GetTextTemplatesIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetTextTemplatesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
