// Code generated by go-swagger; DO NOT EDIT.

package text_template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kben/easybill-rest-api/models"
)

// NewPostTextTemplatesParams creates a new PostTextTemplatesParams object
// with the default values initialized.
func NewPostTextTemplatesParams() *PostTextTemplatesParams {
	var ()
	return &PostTextTemplatesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostTextTemplatesParamsWithTimeout creates a new PostTextTemplatesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostTextTemplatesParamsWithTimeout(timeout time.Duration) *PostTextTemplatesParams {
	var ()
	return &PostTextTemplatesParams{

		timeout: timeout,
	}
}

// NewPostTextTemplatesParamsWithContext creates a new PostTextTemplatesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostTextTemplatesParamsWithContext(ctx context.Context) *PostTextTemplatesParams {
	var ()
	return &PostTextTemplatesParams{

		Context: ctx,
	}
}

// NewPostTextTemplatesParamsWithHTTPClient creates a new PostTextTemplatesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostTextTemplatesParamsWithHTTPClient(client *http.Client) *PostTextTemplatesParams {
	var ()
	return &PostTextTemplatesParams{
		HTTPClient: client,
	}
}

/*PostTextTemplatesParams contains all the parameters to send to the API endpoint
for the post text templates operation typically these are written to a http.Request
*/
type PostTextTemplatesParams struct {

	/*Body*/
	Body *models.TextTemplate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post text templates params
func (o *PostTextTemplatesParams) WithTimeout(timeout time.Duration) *PostTextTemplatesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post text templates params
func (o *PostTextTemplatesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post text templates params
func (o *PostTextTemplatesParams) WithContext(ctx context.Context) *PostTextTemplatesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post text templates params
func (o *PostTextTemplatesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post text templates params
func (o *PostTextTemplatesParams) WithHTTPClient(client *http.Client) *PostTextTemplatesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post text templates params
func (o *PostTextTemplatesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post text templates params
func (o *PostTextTemplatesParams) WithBody(body *models.TextTemplate) *PostTextTemplatesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post text templates params
func (o *PostTextTemplatesParams) SetBody(body *models.TextTemplate) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostTextTemplatesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
