// Code generated by go-swagger; DO NOT EDIT.

package webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/easybill-rest-api/models"
)

// GetWebhooksReader is a Reader for the GetWebhooks structure.
type GetWebhooksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWebhooksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetWebhooksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 429:
		result := NewGetWebhooksTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetWebhooksOK creates a GetWebhooksOK with default headers values
func NewGetWebhooksOK() *GetWebhooksOK {
	return &GetWebhooksOK{}
}

/*GetWebhooksOK handles this case with default header values.

Successful operation
*/
type GetWebhooksOK struct {
	Payload *models.WebHooks
}

func (o *GetWebhooksOK) Error() string {
	return fmt.Sprintf("[GET /webhooks][%d] getWebhooksOK  %+v", 200, o.Payload)
}

func (o *GetWebhooksOK) GetPayload() *models.WebHooks {
	return o.Payload
}

func (o *GetWebhooksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WebHooks)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetWebhooksTooManyRequests creates a GetWebhooksTooManyRequests with default headers values
func NewGetWebhooksTooManyRequests() *GetWebhooksTooManyRequests {
	return &GetWebhooksTooManyRequests{}
}

/*GetWebhooksTooManyRequests handles this case with default header values.

Too Many Requests
*/
type GetWebhooksTooManyRequests struct {
}

func (o *GetWebhooksTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /webhooks][%d] getWebhooksTooManyRequests ", 429)
}

func (o *GetWebhooksTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
