// Code generated by go-swagger; DO NOT EDIT.

package webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/easybill-rest-api/models"
)

// PostWebhooksReader is a Reader for the PostWebhooks structure.
type PostWebhooksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostWebhooksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostWebhooksCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 429:
		result := NewPostWebhooksTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostWebhooksCreated creates a PostWebhooksCreated with default headers values
func NewPostWebhooksCreated() *PostWebhooksCreated {
	return &PostWebhooksCreated{}
}

/*PostWebhooksCreated handles this case with default header values.

Successful operation
*/
type PostWebhooksCreated struct {
	Payload *models.WebHook
}

func (o *PostWebhooksCreated) Error() string {
	return fmt.Sprintf("[POST /webhooks][%d] postWebhooksCreated  %+v", 201, o.Payload)
}

func (o *PostWebhooksCreated) GetPayload() *models.WebHook {
	return o.Payload
}

func (o *PostWebhooksCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WebHook)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostWebhooksTooManyRequests creates a PostWebhooksTooManyRequests with default headers values
func NewPostWebhooksTooManyRequests() *PostWebhooksTooManyRequests {
	return &PostWebhooksTooManyRequests{}
}

/*PostWebhooksTooManyRequests handles this case with default header values.

Too Many Requests
*/
type PostWebhooksTooManyRequests struct {
}

func (o *PostWebhooksTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /webhooks][%d] postWebhooksTooManyRequests ", 429)
}

func (o *PostWebhooksTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
