// Code generated by go-swagger; DO NOT EDIT.

package webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new webhook API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for webhook API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteWebhooksID(params *DeleteWebhooksIDParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteWebhooksIDNoContent, error)

	GetWebhooks(params *GetWebhooksParams, authInfo runtime.ClientAuthInfoWriter) (*GetWebhooksOK, error)

	GetWebhooksID(params *GetWebhooksIDParams, authInfo runtime.ClientAuthInfoWriter) (*GetWebhooksIDOK, error)

	PostWebhooks(params *PostWebhooksParams, authInfo runtime.ClientAuthInfoWriter) (*PostWebhooksCreated, error)

	PutWebhooksID(params *PutWebhooksIDParams, authInfo runtime.ClientAuthInfoWriter) (*PutWebhooksIDOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  DeleteWebhooksID deletes web hook
*/
func (a *Client) DeleteWebhooksID(params *DeleteWebhooksIDParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteWebhooksIDNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteWebhooksIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "DeleteWebhooksID",
		Method:             "DELETE",
		PathPattern:        "/webhooks/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteWebhooksIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteWebhooksIDNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteWebhooksID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetWebhooks fetches web hooks list
*/
func (a *Client) GetWebhooks(params *GetWebhooksParams, authInfo runtime.ClientAuthInfoWriter) (*GetWebhooksOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetWebhooksParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetWebhooks",
		Method:             "GET",
		PathPattern:        "/webhooks",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetWebhooksReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetWebhooksOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetWebhooks: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetWebhooksID fetches web hook
*/
func (a *Client) GetWebhooksID(params *GetWebhooksIDParams, authInfo runtime.ClientAuthInfoWriter) (*GetWebhooksIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetWebhooksIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetWebhooksID",
		Method:             "GET",
		PathPattern:        "/webhooks/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetWebhooksIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetWebhooksIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetWebhooksID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PostWebhooks creates web hook
*/
func (a *Client) PostWebhooks(params *PostWebhooksParams, authInfo runtime.ClientAuthInfoWriter) (*PostWebhooksCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostWebhooksParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PostWebhooks",
		Method:             "POST",
		PathPattern:        "/webhooks",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostWebhooksReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostWebhooksCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostWebhooks: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PutWebhooksID updates web hook
*/
func (a *Client) PutWebhooksID(params *PutWebhooksIDParams, authInfo runtime.ClientAuthInfoWriter) (*PutWebhooksIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPutWebhooksIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PutWebhooksID",
		Method:             "PUT",
		PathPattern:        "/webhooks/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PutWebhooksIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PutWebhooksIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutWebhooksID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
