// Code generated by go-swagger; DO NOT EDIT.

package serial_number

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteSerialNumbersIDReader is a Reader for the DeleteSerialNumbersID structure.
type DeleteSerialNumbersIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSerialNumbersIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteSerialNumbersIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteSerialNumbersIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteSerialNumbersIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewDeleteSerialNumbersIDTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteSerialNumbersIDNoContent creates a DeleteSerialNumbersIDNoContent with default headers values
func NewDeleteSerialNumbersIDNoContent() *DeleteSerialNumbersIDNoContent {
	return &DeleteSerialNumbersIDNoContent{}
}

/*DeleteSerialNumbersIDNoContent handles this case with default header values.

Successful operation
*/
type DeleteSerialNumbersIDNoContent struct {
}

func (o *DeleteSerialNumbersIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /serial-numbers/{id}][%d] deleteSerialNumbersIdNoContent ", 204)
}

func (o *DeleteSerialNumbersIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSerialNumbersIDBadRequest creates a DeleteSerialNumbersIDBadRequest with default headers values
func NewDeleteSerialNumbersIDBadRequest() *DeleteSerialNumbersIDBadRequest {
	return &DeleteSerialNumbersIDBadRequest{}
}

/*DeleteSerialNumbersIDBadRequest handles this case with default header values.

Serial number in use. Operation failed.
*/
type DeleteSerialNumbersIDBadRequest struct {
}

func (o *DeleteSerialNumbersIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /serial-numbers/{id}][%d] deleteSerialNumbersIdBadRequest ", 400)
}

func (o *DeleteSerialNumbersIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSerialNumbersIDNotFound creates a DeleteSerialNumbersIDNotFound with default headers values
func NewDeleteSerialNumbersIDNotFound() *DeleteSerialNumbersIDNotFound {
	return &DeleteSerialNumbersIDNotFound{}
}

/*DeleteSerialNumbersIDNotFound handles this case with default header values.

Not found
*/
type DeleteSerialNumbersIDNotFound struct {
}

func (o *DeleteSerialNumbersIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /serial-numbers/{id}][%d] deleteSerialNumbersIdNotFound ", 404)
}

func (o *DeleteSerialNumbersIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSerialNumbersIDTooManyRequests creates a DeleteSerialNumbersIDTooManyRequests with default headers values
func NewDeleteSerialNumbersIDTooManyRequests() *DeleteSerialNumbersIDTooManyRequests {
	return &DeleteSerialNumbersIDTooManyRequests{}
}

/*DeleteSerialNumbersIDTooManyRequests handles this case with default header values.

Too Many Requests
*/
type DeleteSerialNumbersIDTooManyRequests struct {
}

func (o *DeleteSerialNumbersIDTooManyRequests) Error() string {
	return fmt.Sprintf("[DELETE /serial-numbers/{id}][%d] deleteSerialNumbersIdTooManyRequests ", 429)
}

func (o *DeleteSerialNumbersIDTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
