// Code generated by go-swagger; DO NOT EDIT.

package discount

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteDiscountsPositionIDParams creates a new DeleteDiscountsPositionIDParams object
// with the default values initialized.
func NewDeleteDiscountsPositionIDParams() *DeleteDiscountsPositionIDParams {
	var ()
	return &DeleteDiscountsPositionIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDiscountsPositionIDParamsWithTimeout creates a new DeleteDiscountsPositionIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteDiscountsPositionIDParamsWithTimeout(timeout time.Duration) *DeleteDiscountsPositionIDParams {
	var ()
	return &DeleteDiscountsPositionIDParams{

		timeout: timeout,
	}
}

// NewDeleteDiscountsPositionIDParamsWithContext creates a new DeleteDiscountsPositionIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteDiscountsPositionIDParamsWithContext(ctx context.Context) *DeleteDiscountsPositionIDParams {
	var ()
	return &DeleteDiscountsPositionIDParams{

		Context: ctx,
	}
}

// NewDeleteDiscountsPositionIDParamsWithHTTPClient creates a new DeleteDiscountsPositionIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteDiscountsPositionIDParamsWithHTTPClient(client *http.Client) *DeleteDiscountsPositionIDParams {
	var ()
	return &DeleteDiscountsPositionIDParams{
		HTTPClient: client,
	}
}

/*DeleteDiscountsPositionIDParams contains all the parameters to send to the API endpoint
for the delete discounts position ID operation typically these are written to a http.Request
*/
type DeleteDiscountsPositionIDParams struct {

	/*ID
	  ID of the to be soon deleted discount

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete discounts position ID params
func (o *DeleteDiscountsPositionIDParams) WithTimeout(timeout time.Duration) *DeleteDiscountsPositionIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete discounts position ID params
func (o *DeleteDiscountsPositionIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete discounts position ID params
func (o *DeleteDiscountsPositionIDParams) WithContext(ctx context.Context) *DeleteDiscountsPositionIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete discounts position ID params
func (o *DeleteDiscountsPositionIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete discounts position ID params
func (o *DeleteDiscountsPositionIDParams) WithHTTPClient(client *http.Client) *DeleteDiscountsPositionIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete discounts position ID params
func (o *DeleteDiscountsPositionIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete discounts position ID params
func (o *DeleteDiscountsPositionIDParams) WithID(id int64) *DeleteDiscountsPositionIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete discounts position ID params
func (o *DeleteDiscountsPositionIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDiscountsPositionIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
