// Code generated by go-swagger; DO NOT EDIT.

package discount

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetDiscountsPositionGroupParams creates a new GetDiscountsPositionGroupParams object
// with the default values initialized.
func NewGetDiscountsPositionGroupParams() *GetDiscountsPositionGroupParams {
	var ()
	return &GetDiscountsPositionGroupParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDiscountsPositionGroupParamsWithTimeout creates a new GetDiscountsPositionGroupParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDiscountsPositionGroupParamsWithTimeout(timeout time.Duration) *GetDiscountsPositionGroupParams {
	var ()
	return &GetDiscountsPositionGroupParams{

		timeout: timeout,
	}
}

// NewGetDiscountsPositionGroupParamsWithContext creates a new GetDiscountsPositionGroupParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDiscountsPositionGroupParamsWithContext(ctx context.Context) *GetDiscountsPositionGroupParams {
	var ()
	return &GetDiscountsPositionGroupParams{

		Context: ctx,
	}
}

// NewGetDiscountsPositionGroupParamsWithHTTPClient creates a new GetDiscountsPositionGroupParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDiscountsPositionGroupParamsWithHTTPClient(client *http.Client) *GetDiscountsPositionGroupParams {
	var ()
	return &GetDiscountsPositionGroupParams{
		HTTPClient: client,
	}
}

/*GetDiscountsPositionGroupParams contains all the parameters to send to the API endpoint
for the get discounts position group operation typically these are written to a http.Request
*/
type GetDiscountsPositionGroupParams struct {

	/*CustomerID
	  Filter discounts by customer_id. You can add multiple customer_ids separate by comma like id,id,id.

	*/
	CustomerID *string
	/*Limit
	  Limited the result. Default is 100. Maximum can be 1000.

	*/
	Limit *int64
	/*Page
	  Set current Page. Default is 1.

	*/
	Page *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get discounts position group params
func (o *GetDiscountsPositionGroupParams) WithTimeout(timeout time.Duration) *GetDiscountsPositionGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get discounts position group params
func (o *GetDiscountsPositionGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get discounts position group params
func (o *GetDiscountsPositionGroupParams) WithContext(ctx context.Context) *GetDiscountsPositionGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get discounts position group params
func (o *GetDiscountsPositionGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get discounts position group params
func (o *GetDiscountsPositionGroupParams) WithHTTPClient(client *http.Client) *GetDiscountsPositionGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get discounts position group params
func (o *GetDiscountsPositionGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerID adds the customerID to the get discounts position group params
func (o *GetDiscountsPositionGroupParams) WithCustomerID(customerID *string) *GetDiscountsPositionGroupParams {
	o.SetCustomerID(customerID)
	return o
}

// SetCustomerID adds the customerId to the get discounts position group params
func (o *GetDiscountsPositionGroupParams) SetCustomerID(customerID *string) {
	o.CustomerID = customerID
}

// WithLimit adds the limit to the get discounts position group params
func (o *GetDiscountsPositionGroupParams) WithLimit(limit *int64) *GetDiscountsPositionGroupParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get discounts position group params
func (o *GetDiscountsPositionGroupParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithPage adds the page to the get discounts position group params
func (o *GetDiscountsPositionGroupParams) WithPage(page *int64) *GetDiscountsPositionGroupParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get discounts position group params
func (o *GetDiscountsPositionGroupParams) SetPage(page *int64) {
	o.Page = page
}

// WriteToRequest writes these params to a swagger request
func (o *GetDiscountsPositionGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CustomerID != nil {

		// query param customer_id
		var qrCustomerID string
		if o.CustomerID != nil {
			qrCustomerID = *o.CustomerID
		}
		qCustomerID := qrCustomerID
		if qCustomerID != "" {
			if err := r.SetQueryParam("customer_id", qCustomerID); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Page != nil {

		// query param page
		var qrPage int64
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
