// Code generated by go-swagger; DO NOT EDIT.

package discount

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetDiscountsPositionIDParams creates a new GetDiscountsPositionIDParams object
// with the default values initialized.
func NewGetDiscountsPositionIDParams() *GetDiscountsPositionIDParams {
	var ()
	return &GetDiscountsPositionIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDiscountsPositionIDParamsWithTimeout creates a new GetDiscountsPositionIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDiscountsPositionIDParamsWithTimeout(timeout time.Duration) *GetDiscountsPositionIDParams {
	var ()
	return &GetDiscountsPositionIDParams{

		timeout: timeout,
	}
}

// NewGetDiscountsPositionIDParamsWithContext creates a new GetDiscountsPositionIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDiscountsPositionIDParamsWithContext(ctx context.Context) *GetDiscountsPositionIDParams {
	var ()
	return &GetDiscountsPositionIDParams{

		Context: ctx,
	}
}

// NewGetDiscountsPositionIDParamsWithHTTPClient creates a new GetDiscountsPositionIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDiscountsPositionIDParamsWithHTTPClient(client *http.Client) *GetDiscountsPositionIDParams {
	var ()
	return &GetDiscountsPositionIDParams{
		HTTPClient: client,
	}
}

/*GetDiscountsPositionIDParams contains all the parameters to send to the API endpoint
for the get discounts position ID operation typically these are written to a http.Request
*/
type GetDiscountsPositionIDParams struct {

	/*ID
	  ID of the discount

	*/
	ID int64
	/*Limit
	  Limited the result. Default is 100. Maximum can be 1000.

	*/
	Limit *int64
	/*Page
	  Set current Page. Default is 1.

	*/
	Page *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get discounts position ID params
func (o *GetDiscountsPositionIDParams) WithTimeout(timeout time.Duration) *GetDiscountsPositionIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get discounts position ID params
func (o *GetDiscountsPositionIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get discounts position ID params
func (o *GetDiscountsPositionIDParams) WithContext(ctx context.Context) *GetDiscountsPositionIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get discounts position ID params
func (o *GetDiscountsPositionIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get discounts position ID params
func (o *GetDiscountsPositionIDParams) WithHTTPClient(client *http.Client) *GetDiscountsPositionIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get discounts position ID params
func (o *GetDiscountsPositionIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get discounts position ID params
func (o *GetDiscountsPositionIDParams) WithID(id int64) *GetDiscountsPositionIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get discounts position ID params
func (o *GetDiscountsPositionIDParams) SetID(id int64) {
	o.ID = id
}

// WithLimit adds the limit to the get discounts position ID params
func (o *GetDiscountsPositionIDParams) WithLimit(limit *int64) *GetDiscountsPositionIDParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get discounts position ID params
func (o *GetDiscountsPositionIDParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithPage adds the page to the get discounts position ID params
func (o *GetDiscountsPositionIDParams) WithPage(page *int64) *GetDiscountsPositionIDParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get discounts position ID params
func (o *GetDiscountsPositionIDParams) SetPage(page *int64) {
	o.Page = page
}

// WriteToRequest writes these params to a swagger request
func (o *GetDiscountsPositionIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Page != nil {

		// query param page
		var qrPage int64
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
