// Code generated by go-swagger; DO NOT EDIT.

package discount

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/easybill-rest-api/models"
)

// PostDiscountsPositionReader is a Reader for the PostDiscountsPosition structure.
type PostDiscountsPositionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostDiscountsPositionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostDiscountsPositionCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 429:
		result := NewPostDiscountsPositionTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostDiscountsPositionCreated creates a PostDiscountsPositionCreated with default headers values
func NewPostDiscountsPositionCreated() *PostDiscountsPositionCreated {
	return &PostDiscountsPositionCreated{}
}

/*PostDiscountsPositionCreated handles this case with default header values.

Successful operation
*/
type PostDiscountsPositionCreated struct {
	Payload *models.DiscountPosition
}

func (o *PostDiscountsPositionCreated) Error() string {
	return fmt.Sprintf("[POST /discounts/position][%d] postDiscountsPositionCreated  %+v", 201, o.Payload)
}

func (o *PostDiscountsPositionCreated) GetPayload() *models.DiscountPosition {
	return o.Payload
}

func (o *PostDiscountsPositionCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DiscountPosition)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDiscountsPositionTooManyRequests creates a PostDiscountsPositionTooManyRequests with default headers values
func NewPostDiscountsPositionTooManyRequests() *PostDiscountsPositionTooManyRequests {
	return &PostDiscountsPositionTooManyRequests{}
}

/*PostDiscountsPositionTooManyRequests handles this case with default header values.

Too Many Requests
*/
type PostDiscountsPositionTooManyRequests struct {
}

func (o *PostDiscountsPositionTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /discounts/position][%d] postDiscountsPositionTooManyRequests ", 429)
}

func (o *PostDiscountsPositionTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
