// Code generated by go-swagger; DO NOT EDIT.

package discount

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/kben/easybill-rest-api/models"
)

// NewPutDiscountsPositionGroupIDParams creates a new PutDiscountsPositionGroupIDParams object
// with the default values initialized.
func NewPutDiscountsPositionGroupIDParams() *PutDiscountsPositionGroupIDParams {
	var ()
	return &PutDiscountsPositionGroupIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutDiscountsPositionGroupIDParamsWithTimeout creates a new PutDiscountsPositionGroupIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutDiscountsPositionGroupIDParamsWithTimeout(timeout time.Duration) *PutDiscountsPositionGroupIDParams {
	var ()
	return &PutDiscountsPositionGroupIDParams{

		timeout: timeout,
	}
}

// NewPutDiscountsPositionGroupIDParamsWithContext creates a new PutDiscountsPositionGroupIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutDiscountsPositionGroupIDParamsWithContext(ctx context.Context) *PutDiscountsPositionGroupIDParams {
	var ()
	return &PutDiscountsPositionGroupIDParams{

		Context: ctx,
	}
}

// NewPutDiscountsPositionGroupIDParamsWithHTTPClient creates a new PutDiscountsPositionGroupIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutDiscountsPositionGroupIDParamsWithHTTPClient(client *http.Client) *PutDiscountsPositionGroupIDParams {
	var ()
	return &PutDiscountsPositionGroupIDParams{
		HTTPClient: client,
	}
}

/*PutDiscountsPositionGroupIDParams contains all the parameters to send to the API endpoint
for the put discounts position group ID operation typically these are written to a http.Request
*/
type PutDiscountsPositionGroupIDParams struct {

	/*Body*/
	Body *models.DiscountPositionGroup
	/*ID
	  ID of the to be soon updated discount

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put discounts position group ID params
func (o *PutDiscountsPositionGroupIDParams) WithTimeout(timeout time.Duration) *PutDiscountsPositionGroupIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put discounts position group ID params
func (o *PutDiscountsPositionGroupIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put discounts position group ID params
func (o *PutDiscountsPositionGroupIDParams) WithContext(ctx context.Context) *PutDiscountsPositionGroupIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put discounts position group ID params
func (o *PutDiscountsPositionGroupIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put discounts position group ID params
func (o *PutDiscountsPositionGroupIDParams) WithHTTPClient(client *http.Client) *PutDiscountsPositionGroupIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put discounts position group ID params
func (o *PutDiscountsPositionGroupIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put discounts position group ID params
func (o *PutDiscountsPositionGroupIDParams) WithBody(body *models.DiscountPositionGroup) *PutDiscountsPositionGroupIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put discounts position group ID params
func (o *PutDiscountsPositionGroupIDParams) SetBody(body *models.DiscountPositionGroup) {
	o.Body = body
}

// WithID adds the id to the put discounts position group ID params
func (o *PutDiscountsPositionGroupIDParams) WithID(id int64) *PutDiscountsPositionGroupIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put discounts position group ID params
func (o *PutDiscountsPositionGroupIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutDiscountsPositionGroupIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
