// Code generated by go-swagger; DO NOT EDIT.

package position_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeletePositionGroupsIDParams creates a new DeletePositionGroupsIDParams object
// with the default values initialized.
func NewDeletePositionGroupsIDParams() *DeletePositionGroupsIDParams {
	var ()
	return &DeletePositionGroupsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeletePositionGroupsIDParamsWithTimeout creates a new DeletePositionGroupsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeletePositionGroupsIDParamsWithTimeout(timeout time.Duration) *DeletePositionGroupsIDParams {
	var ()
	return &DeletePositionGroupsIDParams{

		timeout: timeout,
	}
}

// NewDeletePositionGroupsIDParamsWithContext creates a new DeletePositionGroupsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeletePositionGroupsIDParamsWithContext(ctx context.Context) *DeletePositionGroupsIDParams {
	var ()
	return &DeletePositionGroupsIDParams{

		Context: ctx,
	}
}

// NewDeletePositionGroupsIDParamsWithHTTPClient creates a new DeletePositionGroupsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeletePositionGroupsIDParamsWithHTTPClient(client *http.Client) *DeletePositionGroupsIDParams {
	var ()
	return &DeletePositionGroupsIDParams{
		HTTPClient: client,
	}
}

/*DeletePositionGroupsIDParams contains all the parameters to send to the API endpoint
for the delete position groups ID operation typically these are written to a http.Request
*/
type DeletePositionGroupsIDParams struct {

	/*ID
	  ID of position group

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete position groups ID params
func (o *DeletePositionGroupsIDParams) WithTimeout(timeout time.Duration) *DeletePositionGroupsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete position groups ID params
func (o *DeletePositionGroupsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete position groups ID params
func (o *DeletePositionGroupsIDParams) WithContext(ctx context.Context) *DeletePositionGroupsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete position groups ID params
func (o *DeletePositionGroupsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete position groups ID params
func (o *DeletePositionGroupsIDParams) WithHTTPClient(client *http.Client) *DeletePositionGroupsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete position groups ID params
func (o *DeletePositionGroupsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete position groups ID params
func (o *DeletePositionGroupsIDParams) WithID(id int64) *DeletePositionGroupsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete position groups ID params
func (o *DeletePositionGroupsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePositionGroupsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
