// Code generated by go-swagger; DO NOT EDIT.

package position_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/easybill-rest-api/models"
)

// GetPositionGroupsReader is a Reader for the GetPositionGroups structure.
type GetPositionGroupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPositionGroupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPositionGroupsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 429:
		result := NewGetPositionGroupsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPositionGroupsOK creates a GetPositionGroupsOK with default headers values
func NewGetPositionGroupsOK() *GetPositionGroupsOK {
	return &GetPositionGroupsOK{}
}

/*GetPositionGroupsOK handles this case with default header values.

Successful operation
*/
type GetPositionGroupsOK struct {
	Payload *models.PositionGroups
}

func (o *GetPositionGroupsOK) Error() string {
	return fmt.Sprintf("[GET /position-groups][%d] getPositionGroupsOK  %+v", 200, o.Payload)
}

func (o *GetPositionGroupsOK) GetPayload() *models.PositionGroups {
	return o.Payload
}

func (o *GetPositionGroupsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PositionGroups)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPositionGroupsTooManyRequests creates a GetPositionGroupsTooManyRequests with default headers values
func NewGetPositionGroupsTooManyRequests() *GetPositionGroupsTooManyRequests {
	return &GetPositionGroupsTooManyRequests{}
}

/*GetPositionGroupsTooManyRequests handles this case with default header values.

Too Many Requests
*/
type GetPositionGroupsTooManyRequests struct {
}

func (o *GetPositionGroupsTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /position-groups][%d] getPositionGroupsTooManyRequests ", 429)
}

func (o *GetPositionGroupsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
