// Code generated by go-swagger; DO NOT EDIT.

package pdf_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPdfTemplatesParams creates a new GetPdfTemplatesParams object
// with the default values initialized.
func NewGetPdfTemplatesParams() *GetPdfTemplatesParams {

	return &GetPdfTemplatesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPdfTemplatesParamsWithTimeout creates a new GetPdfTemplatesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPdfTemplatesParamsWithTimeout(timeout time.Duration) *GetPdfTemplatesParams {

	return &GetPdfTemplatesParams{

		timeout: timeout,
	}
}

// NewGetPdfTemplatesParamsWithContext creates a new GetPdfTemplatesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPdfTemplatesParamsWithContext(ctx context.Context) *GetPdfTemplatesParams {

	return &GetPdfTemplatesParams{

		Context: ctx,
	}
}

// NewGetPdfTemplatesParamsWithHTTPClient creates a new GetPdfTemplatesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPdfTemplatesParamsWithHTTPClient(client *http.Client) *GetPdfTemplatesParams {

	return &GetPdfTemplatesParams{
		HTTPClient: client,
	}
}

/*GetPdfTemplatesParams contains all the parameters to send to the API endpoint
for the get pdf templates operation typically these are written to a http.Request
*/
type GetPdfTemplatesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get pdf templates params
func (o *GetPdfTemplatesParams) WithTimeout(timeout time.Duration) *GetPdfTemplatesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get pdf templates params
func (o *GetPdfTemplatesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get pdf templates params
func (o *GetPdfTemplatesParams) WithContext(ctx context.Context) *GetPdfTemplatesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get pdf templates params
func (o *GetPdfTemplatesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get pdf templates params
func (o *GetPdfTemplatesParams) WithHTTPClient(client *http.Client) *GetPdfTemplatesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get pdf templates params
func (o *GetPdfTemplatesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetPdfTemplatesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
