// Code generated by go-swagger; DO NOT EDIT.

package stock

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kben/easybill-rest-api/models"
)

// GetStocksReader is a Reader for the GetStocks structure.
type GetStocksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStocksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetStocksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 429:
		result := NewGetStocksTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetStocksOK creates a GetStocksOK with default headers values
func NewGetStocksOK() *GetStocksOK {
	return &GetStocksOK{}
}

/*GetStocksOK handles this case with default header values.

Successful operation
*/
type GetStocksOK struct {
	Payload *models.Stocks
}

func (o *GetStocksOK) Error() string {
	return fmt.Sprintf("[GET /stocks][%d] getStocksOK  %+v", 200, o.Payload)
}

func (o *GetStocksOK) GetPayload() *models.Stocks {
	return o.Payload
}

func (o *GetStocksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Stocks)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetStocksTooManyRequests creates a GetStocksTooManyRequests with default headers values
func NewGetStocksTooManyRequests() *GetStocksTooManyRequests {
	return &GetStocksTooManyRequests{}
}

/*GetStocksTooManyRequests handles this case with default header values.

Too Many Requests
*/
type GetStocksTooManyRequests struct {
}

func (o *GetStocksTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /stocks][%d] getStocksTooManyRequests ", 429)
}

func (o *GetStocksTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
