// Code generated by go-swagger; DO NOT EDIT.

package stock

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetStocksIDParams creates a new GetStocksIDParams object
// with the default values initialized.
func NewGetStocksIDParams() *GetStocksIDParams {
	var ()
	return &GetStocksIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetStocksIDParamsWithTimeout creates a new GetStocksIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetStocksIDParamsWithTimeout(timeout time.Duration) *GetStocksIDParams {
	var ()
	return &GetStocksIDParams{

		timeout: timeout,
	}
}

// NewGetStocksIDParamsWithContext creates a new GetStocksIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetStocksIDParamsWithContext(ctx context.Context) *GetStocksIDParams {
	var ()
	return &GetStocksIDParams{

		Context: ctx,
	}
}

// NewGetStocksIDParamsWithHTTPClient creates a new GetStocksIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetStocksIDParamsWithHTTPClient(client *http.Client) *GetStocksIDParams {
	var ()
	return &GetStocksIDParams{
		HTTPClient: client,
	}
}

/*GetStocksIDParams contains all the parameters to send to the API endpoint
for the get stocks ID operation typically these are written to a http.Request
*/
type GetStocksIDParams struct {

	/*ID
	  ID of the stock entry that needs to be fetched

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get stocks ID params
func (o *GetStocksIDParams) WithTimeout(timeout time.Duration) *GetStocksIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get stocks ID params
func (o *GetStocksIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get stocks ID params
func (o *GetStocksIDParams) WithContext(ctx context.Context) *GetStocksIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get stocks ID params
func (o *GetStocksIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get stocks ID params
func (o *GetStocksIDParams) WithHTTPClient(client *http.Client) *GetStocksIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get stocks ID params
func (o *GetStocksIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get stocks ID params
func (o *GetStocksIDParams) WithID(id int64) *GetStocksIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get stocks ID params
func (o *GetStocksIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetStocksIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
