// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DiscountPositionGroups discount position groups
//
// swagger:model DiscountPositionGroups
type DiscountPositionGroups struct {
	List

	// items
	Items []*DiscountPositionGroup `json:"items"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *DiscountPositionGroups) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 List
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.List = aO0

	// AO1
	var dataAO1 struct {
		Items []*DiscountPositionGroup `json:"items"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.Items = dataAO1.Items

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m DiscountPositionGroups) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.List)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		Items []*DiscountPositionGroup `json:"items"`
	}

	dataAO1.Items = m.Items

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this discount position groups
func (m *DiscountPositionGroups) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with List
	if err := m.List.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateItems(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DiscountPositionGroups) validateItems(formats strfmt.Registry) error {

	if swag.IsZero(m.Items) { // not required
		return nil
	}

	for i := 0; i < len(m.Items); i++ {
		if swag.IsZero(m.Items[i]) { // not required
			continue
		}

		if m.Items[i] != nil {
			if err := m.Items[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *DiscountPositionGroups) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DiscountPositionGroups) UnmarshalBinary(b []byte) error {
	var res DiscountPositionGroups
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
