// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostBoxRequest post box request
//
// swagger:model PostBoxRequest
type PostBoxRequest struct {

	// cc
	Cc string `json:"cc,omitempty"`

	// date
	// Format: date
	Date strfmt.Date `json:"date,omitempty"`

	// from
	From string `json:"from,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// subject
	Subject string `json:"subject,omitempty"`

	// to
	To string `json:"to,omitempty"`
}

// Validate validates this post box request
func (m *PostBoxRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostBoxRequest) validateDate(formats strfmt.Registry) error {

	if swag.IsZero(m.Date) { // not required
		return nil
	}

	if err := validate.FormatOf("date", "body", "date", m.Date.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostBoxRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostBoxRequest) UnmarshalBinary(b []byte) error {
	var res PostBoxRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
