// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SerialNumber serial number
//
// swagger:model SerialNumber
type SerialNumber struct {

	// created at
	// Read Only: true
	// Format: datetime
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// document id
	// Read Only: true
	DocumentID *int64 `json:"document_id,omitempty"`

	// document position id
	// Read Only: true
	DocumentPositionID *int64 `json:"document_position_id,omitempty"`

	// id
	// Read Only: true
	ID int64 `json:"id,omitempty"`

	// position id
	// Required: true
	PositionID *int64 `json:"position_id"`

	// serial number
	// Required: true
	SerialNumber *string `json:"serial_number"`

	// used at
	// Read Only: true
	// Format: datetime
	UsedAt *strfmt.DateTime `json:"used_at,omitempty"`
}

// Validate validates this serial number
func (m *SerialNumber) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePositionID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSerialNumber(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUsedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SerialNumber) validateCreatedAt(formats strfmt.Registry) error {

	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created_at", "body", "datetime", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *SerialNumber) validatePositionID(formats strfmt.Registry) error {

	if err := validate.Required("position_id", "body", m.PositionID); err != nil {
		return err
	}

	return nil
}

func (m *SerialNumber) validateSerialNumber(formats strfmt.Registry) error {

	if err := validate.Required("serial_number", "body", m.SerialNumber); err != nil {
		return err
	}

	return nil
}

func (m *SerialNumber) validateUsedAt(formats strfmt.Registry) error {

	if swag.IsZero(m.UsedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("used_at", "body", "datetime", m.UsedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SerialNumber) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SerialNumber) UnmarshalBinary(b []byte) error {
	var res SerialNumber
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
